import { Inter,Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ weight:['400','500','700', '900'],subsets: ["latin"] });

export const metadata = {
  title:{
    default: "Next Hero",
    template: "%s | Next Hero"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Navbar/>
        <div>
          {children}
        </div>
        <footer className="bg-blue-400 p-5 text-center">
          This Is My Footer
        </footer>
      </body>
    </html>
  );
}

